import {
  PaperClipCharm,
  WashiTapeCharm,
  TornPaperCharm,
  TinyFlowerCharm,
  PressedFlowerCharm,
  HeartCharm,
  StarCharm,
  ButterflyCharm,
  PostageStampCharm,
  TinyTagCharm,
  NoteCharm,
  PressedLeafCharm,
  TinyBowCharm,
  DoodleCharm,
  DividerCharm,
  ChecklistCharm,
  PinCharm,
  PhotoCornerCharm,
} from '../components/Charms';

/**
 * Each charm sits just outside the card's own padding box — clipped to a
 * corner and mostly hanging above/below the edge — so it never overlaps the
 * title, date, or entry text underneath. `rotate` gives it the slightly
 * imperfect, hand-placed feel real washi tape or a pressed flower would have.
 * Sizes are deliberately generous — these are meant to read as physical
 * stickers/paper pieces stuck onto the page, not small UI glyphs.
 *
 * Keep `value` list in sync with backend/models/Journal.js DECORATIONS.
 */
export const DECORATIONS = [
  { value: 'none', label: 'None', Charm: null },
  {
    value: 'paper-clip',
    label: 'Paper Clip',
    Charm: PaperClipCharm,
    corner: 'top-left',
    width: 30,
    height: 40,
    rotate: -9,
    offset: { top: -16, left: 16 },
  },
  {
    value: 'washi-tape',
    label: 'Washi Tape',
    Charm: WashiTapeCharm,
    corner: 'top-right',
    width: 74,
    height: 28,
    rotate: 6,
    offset: { top: -13, right: 4 },
  },
  {
    value: 'torn-paper',
    label: 'Torn Paper',
    Charm: TornPaperCharm,
    corner: 'bottom-left',
    width: 52,
    height: 40,
    rotate: 7,
    offset: { bottom: -16, left: 8 },
  },
  {
    value: 'tiny-flower',
    label: 'Flower',
    Charm: TinyFlowerCharm,
    corner: 'bottom-right',
    width: 36,
    height: 36,
    rotate: -6,
    offset: { bottom: -15, right: 14 },
  },
  {
    value: 'pressed-flower',
    label: 'Pressed Flower',
    Charm: PressedFlowerCharm,
    corner: 'bottom-left',
    width: 34,
    height: 34,
    rotate: 12,
    offset: { bottom: -13, left: 16 },
  },
  {
    value: 'heart',
    label: 'Heart',
    Charm: HeartCharm,
    corner: 'top-right',
    width: 28,
    height: 24,
    rotate: 10,
    offset: { top: -11, right: 18 },
  },
  {
    value: 'star',
    label: 'Star',
    Charm: StarCharm,
    corner: 'top-left',
    width: 26,
    height: 26,
    rotate: -12,
    offset: { top: -11, left: 18 },
  },
  {
    value: 'butterfly',
    label: 'Butterfly',
    Charm: ButterflyCharm,
    corner: 'top-right',
    width: 42,
    height: 32,
    rotate: -6,
    offset: { top: -15, right: 8 },
  },
  {
    value: 'postage-stamp',
    label: 'Postage Stamp',
    Charm: PostageStampCharm,
    corner: 'top-right',
    width: 34,
    height: 40,
    rotate: 6,
    offset: { top: -17, right: 16 },
  },
  {
    value: 'tiny-tag',
    label: 'Handwritten Tag',
    Charm: TinyTagCharm,
    corner: 'top-left',
    width: 28,
    height: 38,
    rotate: -9,
    offset: { top: -15, left: 18 },
  },
  {
    value: 'note',
    label: 'Handwritten Note',
    Charm: NoteCharm,
    corner: 'bottom-right',
    width: 40,
    height: 40,
    rotate: 3,
    offset: { bottom: -17, right: 12 },
  },
  {
    value: 'pressed-leaf',
    label: 'Pressed Leaf',
    Charm: PressedLeafCharm,
    corner: 'bottom-left',
    width: 26,
    height: 42,
    rotate: -16,
    offset: { bottom: -17, left: 18 },
  },
  {
    value: 'tiny-bow',
    label: 'Ribbon Bow',
    Charm: TinyBowCharm,
    corner: 'top-left',
    width: 40,
    height: 29,
    rotate: 5,
    offset: { top: -12, left: 20 },
  },
  {
    value: 'doodle',
    label: 'Doodle',
    Charm: DoodleCharm,
    corner: 'bottom-right',
    width: 42,
    height: 24,
    rotate: -3,
    offset: { bottom: -9, right: 18 },
  },
  {
    value: 'divider',
    label: 'Hand-drawn Divider',
    Charm: DividerCharm,
    corner: 'bottom-left',
    width: 54,
    height: 14,
    rotate: 2,
    offset: { bottom: -6, left: 6 },
  },
  {
    value: 'checklist',
    label: 'Checklist',
    Charm: ChecklistCharm,
    corner: 'top-right',
    width: 32,
    height: 40,
    rotate: 4,
    offset: { top: -16, right: 14 },
  },
  {
    value: 'pin',
    label: 'Push Pin',
    Charm: PinCharm,
    corner: 'top-right',
    width: 22,
    height: 26,
    rotate: 0,
    offset: { top: -8, right: 20 },
  },
  {
    value: 'photo-corner',
    label: 'Photo Corner',
    Charm: PhotoCornerCharm,
    corner: 'top-left',
    width: 26,
    height: 26,
    rotate: 0,
    offset: { top: 3, left: 3 },
  },
];

/** How many charms a single entry can wear at once, so a card stays readable. */
export const MAX_DECORATIONS = 6;

export const DECORATION_VALUES = DECORATIONS.map((d) => d.value);

const DECORATION_MAP = Object.fromEntries(DECORATIONS.map((d) => [d.value, d]));

export const getDecoration = (value) => DECORATION_MAP[value] || DECORATION_MAP.none;
